version: 0.2

env:
    variables:
        CACHE_CONTROL: "86400"
        S3_BUCKET: "{{s3_bucket_url}}"
        BUILD_FOLDER: "dist"
phases:
  install:
    runtime-versions:
        nodejs: 14
    commands:
        - echo Installing source NPM dependencies...
        - npm install
        - npm install -g @angular/cli
  build:
    commands:
        - echo Build started 
        - ng build
        
  post-build:
    commands: 
        - aws cloudfront create-invalidation --distribution-id E2SQGCQ64GAQDP --paths '/*'
        - aws s3 sync . "s3://angular-app-r" 
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes
